---
ID: "035816f1-5ae2-4c07-ad0d-6d58fb758be7"
Parent: "8828c281-8222-4e4b-b428-ed8b7c31ef76"
Template: "9924ff94-4f8e-416b-a6cc-c782ad789e6e"
Path: /sitecore/system/Uniform/Modules/Optimize/Tracking/Destinations/Google Analytics/Tracking Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200813T133527Z
