---
ID: "14d06266-a4c7-4fb9-be00-eb417a4d5156"
Parent: "959b1145-6351-4585-80dd-51d2e30056ce"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Uniform Platform Canvas/CanvasIntegrationService/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210914T144922Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
