---
ID: "dca71521-5020-49be-a484-4526a55fbbb9"
Parent: "80ed84a1-5b6d-4d7e-8dff-0ab93fd8b4a4"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Uniform/ContentSync/InitialSync/Commands
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210329T041456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
