---
ID: "d941727b-9d51-4f1b-8fba-e6be241c21a7"
Parent: "56fc51c4-6744-4fe0-b437-b3f87a32224e"
Template: "56fc51c4-6744-4fe0-b437-b3f87a32224e"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics/Profile Pattern Mapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200605T035311Z
