---
ID: "3c35c692-d090-4986-88a6-817b114c4b3f"
Parent: "83f57aea-5c9e-41cf-8448-48a8364e4dc7"
Template: "83f57aea-5c9e-41cf-8448-48a8364e4dc7"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics 4/User Dimension Mapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220706T192049Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
