---
ID: "e7a6b5ca-3f9d-4a8a-a964-717070f0532e"
Parent: "0722522f-11dc-46b6-9551-9e0a35548ca3"
Template: "0722522f-11dc-46b6-9551-9e0a35548ca3"
Path: /sitecore/templates/Uniform Optimize/Sitecore Site Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200813T175743Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
