---
ID: "c08d77e5-7a91-4d45-af3d-a309ac422067"
Parent: "17fa3c15-17eb-4c81-a0b8-e6c1d48ab11a"
Template: "17fa3c15-17eb-4c81-a0b8-e6c1d48ab11a"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics UA/Custom Dimension Mapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200605T035055Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
