---
ID: "3fb84829-35b7-4729-b648-717c84dd20b5"
Parent: "69793216-2383-494e-8041-8e4d5cb6bb1b"
Template: "eed39f44-1fef-4544-978a-83ba9e6fac4e"
Path: /sitecore/system/Uniform/Modules/Logging/LogLevels/DISABLED
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230619T111852Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
