---
ID: "ccb1d6c1-bf1a-4f62-af74-6182814094d1"
Parent: "37758cb1-4f4a-4aa0-9afd-e3be7da2deed"
Template: "37758cb1-4f4a-4aa0-9afd-e3be7da2deed"
Path: /sitecore/templates/Uniform/Uniform Root Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230404T185558Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
