---
ID: "035f11f2-b33a-4eb6-8ed2-7803283c80a4"
Parent: "e38a031b-a4a8-4a65-940a-72cc9880ef70"
Template: "e38a031b-a4a8-4a65-940a-72cc9880ef70"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics 4/Tracking Configuration/__Standard Values
DB: master
SharedFields:
- ID: "9cdd0449-9eaa-413e-a63e-21ccb27918ec"
  Hint: ScriptUrl
  Value: //www.googletagmanager.com/gtag/js
- ID: "c95357b7-06d1-402f-804e-411a1cda4a3f"
  Hint: Event name
  Value: uniform_event
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220706T213625Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
