---
ID: "4bf82e51-f7d3-471f-86f2-fb50533ab113"
Parent: "236eea81-894b-4517-985d-61d22aa50a34"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/templates/Uniform/Presets/Branches/SiteContext/$name/Content Sync History
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 1
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210208T152705Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
