---
ID: "b48315ad-8201-4f41-ad7a-f746c63afae2"
Parent: "07cd72a6-3ca8-4974-bbc7-c0f2f31be8f3"
Template: "07cd72a6-3ca8-4974-bbc7-c0f2f31be8f3"
Path: /sitecore/templates/Uniform Optimize/Tracking/Tracker Cookie Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210407T160732Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
