---
ID: "b5329256-7f7d-4aaa-96b7-562104d8cee1"
Parent: "bfca84e7-d500-49cb-be99-7fcf3fd81fc1"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Uniform/Deployment/Core/MediaDeploymentScopeService/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210208T114817Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
