---
ID: "2bb8e469-6c29-4db8-b246-d91480aeda9d"
Parent: "e756bc2b-d81f-4160-8cf9-ae0adb971c05"
Template: "e756bc2b-d81f-4160-8cf9-ae0adb971c05"
Path: /sitecore/templates/Uniform Optimize/Testing/Uniform Sample Size/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200408T145818Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
