---
ID: "0de10ab9-c9d8-4b92-91a8-90075faed663"
Parent: "bd2df16b-fa23-4de2-b39b-dcb8ce12e19e"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Uniform/ItemBasedConfiguration/AttachableService/System
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210106T215219Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
