---
ID: "2ff8df4f-1b56-4a6c-84f2-12bcf2f2bdd9"
Parent: "050be51d-e563-4629-8094-c90b3f49a77f"
Template: "050be51d-e563-4629-8094-c90b3f49a77f"
Path: /sitecore/templates/Uniform Optimize/Tracking/Mapping/Contact Property Value/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200605T055404Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
