---
ID: "4dbbbba9-0d42-4979-a2c7-ab71d3089c6c"
Parent: "28f88862-216d-450a-9024-124230c3203a"
Template: "28f88862-216d-450a-9024-124230c3203a"
Path: /sitecore/templates/Uniform/ContentSync/FileSystem/FileSystemContentSyncService/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210106T221440Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
