---
ID: "fdf5c3a5-4ec5-4fc1-a9e1-7aebdc2639bd"
Parent: "b83ce854-c8b1-4b42-90d7-eb38e504404d"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Uniform/ContentSync/AkamaiNetStorage/AkamaiNetStorageContentSyncService/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210106T110357Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
