---
ID: "ab0b4877-5bee-428d-b7ef-a7edf7a30694"
Parent: "aee91f4f-760c-48f2-bf55-c9f0de3d4c61"
Template: "aee91f4f-760c-48f2-bf55-c9f0de3d4c61"
Path: /sitecore/templates/Uniform/Uniform Item/__Standard Values
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 1
- ID: "9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4"
  Hint: __Read Only
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190403T045822Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
