---
ID: "dbe25be8-6d76-4aa6-a067-f13c96d26c37"
Parent: "7866d5ac-0c2b-4de1-ae84-23d3e8f4179e"
Template: "7866d5ac-0c2b-4de1-ae84-23d3e8f4179e"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics 4/Contact Property Mapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220706T192036Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
