---
ID: "bead8241-8864-43ef-9abb-cbf6e3174418"
Parent: "84a60d15-5823-4462-af0d-f5f150c03363"
Template: "84a60d15-5823-4462-af0d-f5f150c03363"
Path: /sitecore/templates/Uniform Optimize/Tracking/Oracle DMP/Campaign Property/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201026T005914Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
