---
ID: "0751c18d-6d00-42f2-90b3-170d3dd6df51"
Parent: "1afc21e7-2eee-4101-adda-8c2fe398f8a5"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Uniform/Deployment/HostedService/HostedDeploymentService/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210106T110108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
