---
ID: "37538c66-4288-4e3a-8097-ad3b0ce1c9b2"
Parent: "c381a08c-f128-4ce8-8bc4-c2065f76a953"
Template: "0370c033-1ba2-4819-bbc8-7d62ed61c9e3"
Path: /sitecore/system/Uniform/Modules/Optimize/Personalization/Emitters/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210511T005751Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
