---
ID: "86d56537-aee2-4b05-9fbf-5cfe2376e94d"
Parent: "9bbcd547-3117-4315-908e-86c923fa386a"
Template: "9bbcd547-3117-4315-908e-86c923fa386a"
Path: /sitecore/templates/Uniform Optimize/Tracking/Oracle DMP/Container/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200922T201348Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
