---
ID: "ccf33e64-26b5-48ba-a65c-2a95a5a7048a"
Parent: "cda16873-6b24-4755-aa6e-23bf419f34eb"
Template: "ec6d62a5-5d00-4329-8958-8ac1ad100ebb"
Path: /sitecore/content/Applications/Content Editor/Ribbons/Strips/Uniform
DB: core
SharedFields:
- ID: "12c1ceb4-f549-472a-97ed-99bff70eb84e"
  Hint: ID
  Value: UniformStrip
- ID: "59de8e82-a9bc-4862-bbee-f5567dd63b65"
  Hint: Access Key
  Value: U
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200410T171641Z
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: Uniform
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
