---
ID: "b64ac5f8-45cf-4b2e-9a6e-100d29b61639"
Parent: "2bd7f36e-62f6-4016-9213-fbd45b281863"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/system/Uniform/Modules/Purge/Akamai/Networks
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210517T124059Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
