---
ID: "0cd22bf3-b537-46eb-b4a2-e8e0a7ef93c6"
Parent: "d1bf29a2-f6ba-42aa-b656-c3eb61894191"
Template: "d1bf29a2-f6ba-42aa-b656-c3eb61894191"
Path: /sitecore/templates/Uniform Optimize/Tracking/Google Analytics UA/Property/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200813T214115Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
