---
ID: "c1fd6b1a-a25b-49ee-a83f-1be645099e92"
Parent: "e57783d1-9d29-4168-a8ef-dfcbfdca089e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/system/Uniform/Modules/Optimize/Tracking/Destinations/Sitecore xDB/Tracking Configurations
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{3281B003-10B7-4D67-A078-FE3E7015975D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200922T001249Z
