---
ID: "269b4e29-0335-4d55-9a69-786bcc2b7c2b"
Parent: "c69cd700-92eb-43ac-b73e-305060f377c1"
Template: "c69cd700-92eb-43ac-b73e-305060f377c1"
Path: /sitecore/templates/Uniform Optimize/Tracking/Throttled Cookie/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210407T161258Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
